nav:
  Home: /
  About: /about/
  Blog: /archives/
  Imprint: /imprint/

customize:
    gravatar:
        email: ferdinand@muetsch.io
    logo:
        enabled: true
        width: 50
        height: 50
        gravatar: true
    favicon: 
      # eg. generate with http://realfavicongenerator.net/
      desktop:
        url: favicon.ico
        gravatar: false
      android:
        url: favicon.ico
        gravator: false
    social_links:
        github:
            iconset: fab
            url: http://github.com/muety
        mastodon:
            iconset: fab
            url: https://social.tchncs.de/web/accounts/106761076750920593
        linkedin:
            iconset: fab
            url: https://www.linkedin.com/in/ferdinand-m%C3%BCtsch-246734139/
        telegram:
            iconset: fab
            url: https://telegram.me/n1try
        money-bill:
            iconset: fas
            url: https://liberapay.com/muety/
        envelope:
            iconset: far
            url: mailto:ferdinand@muetsch.io
    me_links:
        github: http://github.com/muety
        mastodon: https://social.tchncs.de/web/accounts/106761076750920593
        mail: mailto:ferdinand@muetsch.io
    webmention_endpoint: https://webmention.io/muetsch.io/webmention
    pingback_endpoint: https://webmention.io/muetsch.io/xmlrpc
    show_all_posts: false
    post_count: 6
    highlight: rainbow

# RSS
rss: false

# Plugins
plugins:
    disqus_shortname:
    google_analytics:

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus: